### ISSUE TITLE
Negative Self Thought Text Particles

### ISSUE THREAD

**Issue by graceanders** [IAMColumbia/Doubts_Dungeon#43]

**Comment by marpl6967** [comment]
Create a particle in Unity that has text bubble up from the floor to add environmental storytelling to further enunciate the themes of mental health within a playable space

**Comment by marpl6967** [comment]
Like this

https://www.youtube.com/watch?v=NrfAH4r7blA

or this

https://www.youtube.com/watch?v=E2AA-EgjbIw
